[versions]
androidGradle = "9.3.0"
kotlin = "2.3.21"
ktLint = "12.1.1"
detekt = "1.23.6"

[libraries]
android-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradle" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }